name:                repro
version:             0.1.0.0
github:              "oadams/repro"
license:             BSD-3-Clause
author:              "Oliver Adams"
maintainer:          "oliver.adams@gmail.com"
copyright:           "2023 Oliver Adams"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oadams/repro#readme>

dependencies:
- base >= 4.7 && < 5
- HsYAML
- text
- bytestring
- containers
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  repro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repro
    - containers
    - process
    - HsYAML
    - text

tests:
  repro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repro
    - tasty
    - tasty-hunit
